# Generated by Django 3.2 on 2023-03-31 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idAmbiente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAmbiente', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100, blank=False)),
            ],
            options={
                'ordering': ['NombreAmbiente'],
            },
        ),
        migrations.CreateModel(
            name='CambioHW',
            fields=[
                ('idHW', models.AutoField(primary_key=True, serialize=False)),
                ('NombreHW', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['idHW'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Categoria'],
            },
        ),
        migrations.CreateModel(
            name='cierreFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFalla', models.CharField(blank=True, max_length=150, verbose_name='Service Request')),
                ('ComentarioCierre', models.TextField(null=True, verbose_name='Comentario')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idComponente', models.AutoField(primary_key=True, serialize=False)),
                ('Componente', models.CharField(max_length=100)),
                ('idVendor',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.vendor', verbose_name='Vendor'))
            ],
            options={
                'ordering': ['Componente'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('idVendor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreVendor', models.CharField(max_length=100)),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.categoria', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['NombreVendor'],
            },
        ),
        migrations.CreateModel(
            name='reporteFallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR', models.CharField(blank=True, max_length=150, verbose_name='Service Request')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('Fecha', models.CharField(max_length=50)),
                ('RMA', models.CharField(blank=True, max_length=150)),
                ('RFC', models.CharField(blank=True, max_length=50)),
                ('IM', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.ambiente', verbose_name='Ambiente')),
                ('CambioHW', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cambiohw', verbose_name='Cambio de hardware')),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.categoria', verbose_name='Categoria')),
                ('Componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.componente', verbose_name='Componente')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActividad', models.CharField(blank=True, max_length=150, verbose_name='Actividad')),
                ('FechaInicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Inicio')),
                ('FechaFin', models.CharField(blank=True, max_length=150, verbose_name='Fecha Fin')),
                ('HorasInvertidas', models.CharField(blank=True, max_length=50, verbose_name='Horas invertidas')),
                ('IM', models.CharField(blank=True, max_length=150, verbose_name='IM')),
                ('RFC', models.CharField(blank=True, max_length=150, verbose_name='RFC')),
                ('SR', models.CharField(blank=True, max_length=150, verbose_name='SR')),
                ('Usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('Evento', models.CharField(blank=True, max_length=150, verbose_name='Evento')),
                ('Descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Status', models.CharField(blank=True, max_length=150, verbose_name='Status')),
                ('Avance', models.CharField(blank=True, max_length=150, verbose_name='Avance')),
                ('Solicitante', models.CharField(blank=True, max_length=100, verbose_name='Solicitante')),
                ('NombreTurnos', models.CharField(blank=True, max_length=100, verbose_name='NombreTurnos')),
                ('Ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.ambiente', verbose_name='Ambiente')),
                ('HO', models.CharField(max_length=100, blank=True, verbose_name="Home Office")),
                ('Tipo', models.CharField(max_length=100, blank=True, verbose_name="Tipo mejora")),
            ],
        ),
    ]
