# Generated by Django 4.0.2 on 2022-02-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idAmbiente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAmbiente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CambioHW',
            fields=[
                ('idHW', models.AutoField(primary_key=True, serialize=False)),
                ('NombreHW', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('idVendor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreVendor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reporteFallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Motivo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.ambiente', verbose_name='Ambiente')),
                ('CambioHW', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.cambiohw', verbose_name='CambioHW')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
