# Generated by Django 3.2 on 2025-05-09 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idAmbiente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAmbiente', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['NombreAmbiente'],
            },
        ),
        migrations.CreateModel(
            name='CambioHW',
            fields=[
                ('idHW', models.AutoField(primary_key=True, serialize=False)),
                ('NombreHW', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['idHW'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Categoria'],
            },
        ),
        migrations.CreateModel(
            name='cierreFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFalla', models.CharField(blank=True, max_length=150, verbose_name='Service Request')),
                ('ComentarioCierre', models.TextField(null=True, verbose_name='Comentario')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('idCloud', models.AutoField(primary_key=True, serialize=False)),
                ('Cloud', models.CharField(blank=True, max_length=200, verbose_name='Cloud')),
                ('metadata', models.CharField(blank=True, max_length=20, verbose_name='tipoMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idComponente', models.AutoField(primary_key=True, serialize=False)),
                ('Componente', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Componente'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder', models.CharField(blank=True, max_length=200, verbose_name='Folder')),
                ('idCloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='ingActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreIngeniero', models.CharField(blank=True, max_length=1000, verbose_name='Ing. Asignado')),
                ('Proyecto', models.CharField(blank=True, max_length=150, verbose_name='Proyecto')),
                ('Avance', models.CharField(blank=True, max_length=150, verbose_name='Avance')),
                ('Status', models.CharField(blank=True, max_length=150, verbose_name='Status')),
                ('FechaAsignacion', models.DateTimeField(blank=True, verbose_name='Fecha asignación')),
                ('FechaFinal', models.DateTimeField(blank=True, verbose_name='Fecha final')),
                ('LiderTecnico', models.CharField(blank=True, max_length=150, verbose_name='Ing. Asignado')),
            ],
        ),
        migrations.CreateModel(
            name='metadataORG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idORG', models.CharField(blank=True, max_length=150, verbose_name='ID Org')),
                ('ORGname', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('SAP', models.CharField(blank=True, max_length=5000, verbose_name='SAP')),
                ('TipoContratacion', models.CharField(blank=True, max_length=5000, verbose_name='Tipo Contratacion')),
                ('SA_Panel', models.CharField(blank=True, max_length=5000, verbose_name='SA Panel')),
                ('UUID', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='metadataORGvDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idORG', models.CharField(blank=True, max_length=150, verbose_name='ID Org')),
                ('Campo', models.CharField(blank=True, max_length=20, verbose_name='Campo')),
                ('Valor', models.CharField(blank=True, max_length=250, verbose_name='Valor')),
                ('UUID', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='metadataVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idORG', models.CharField(blank=True, max_length=150, verbose_name='ID Org')),
                ('VM', models.CharField(blank=True, max_length=250, verbose_name='VM')),
                ('cpu', models.CharField(blank=True, max_length=150, verbose_name='CPU')),
                ('memoria', models.CharField(blank=True, max_length=150, verbose_name='Memoria')),
                ('host', models.CharField(blank=True, max_length=150, verbose_name='ESX')),
                ('computePolicy', models.CharField(blank=True, max_length=150, verbose_name='Compute')),
                ('idVM', models.CharField(blank=True, max_length=150, verbose_name='IDVM')),
                ('hdd', models.CharField(blank=True, max_length=150, verbose_name='HDD')),
                ('UUID', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='vmESX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvCenter', models.CharField(blank=True, max_length=150, verbose_name='vCenter')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('VM', models.CharField(blank=True, max_length=150, verbose_name='VM')),
                ('State', models.CharField(blank=True, max_length=150, verbose_name='Estado')),
                ('idCloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('idVendor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreVendor', models.CharField(max_length=100)),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.categoria', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['NombreVendor'],
            },
        ),
        migrations.CreateModel(
            name='reporteFallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR', models.CharField(blank=True, max_length=150, verbose_name='Service Request')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('Fecha', models.CharField(max_length=50)),
                ('FechaFix', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('RMA', models.CharField(blank=True, max_length=150)),
                ('RFC', models.CharField(blank=True, max_length=50)),
                ('IM', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('FechaHoraSolicitud', models.CharField(blank=True, max_length=150, verbose_name='Fecha Solicitud')),
                ('FechaPrimerContacto', models.CharField(blank=True, max_length=150, verbose_name='Fecha Primer Contacto')),
                ('FechaCierre', models.CharField(blank=True, max_length=150, verbose_name='Fecha Cierre')),
                ('EstatusSR', models.CharField(blank=True, max_length=150, verbose_name='Estatus')),
                ('Severidad', models.CharField(blank=True, max_length=150, verbose_name='Severidad')),
                ('Resolucion', models.CharField(blank=True, max_length=150, verbose_name='Resolución')),
                ('Ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.ambiente', verbose_name='Ambiente')),
                ('CambioHW', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cambiohw', verbose_name='Cambio de hardware')),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.categoria', verbose_name='Categoria')),
                ('Componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.componente', verbose_name='Componente')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='kpisORG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG', models.CharField(blank=True, max_length=150, verbose_name='Organización')),
                ('ORGvDC', models.CharField(blank=True, max_length=150, verbose_name='Nombre OrgvDC')),
                ('NombreORG', models.CharField(blank=True, max_length=150, verbose_name='Nombre Organización')),
                ('vApp', models.CharField(blank=True, max_length=150, verbose_name='Nombre vApp')),
                ('VM', models.CharField(blank=True, max_length=150, verbose_name='Nombre VM')),
                ('OS', models.CharField(blank=True, max_length=150, verbose_name='Sistema Operativo')),
                ('NoUsuarios', models.CharField(blank=True, max_length=150, verbose_name='No Usuarios')),
                ('FechaAlta', models.CharField(blank=True, max_length=150, verbose_name='Fecha Alta')),
                ('timestamp', models.DateTimeField(blank=True, verbose_name='Timestamp')),
                ('Suscripcion', models.CharField(blank=True, max_length=150, verbose_name='Suscripcion')),
                ('UUID', models.UUIDField(default=uuid.uuid4)),
                ('idCloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='Keepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('Usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('Password', models.CharField(blank=True, max_length=150, verbose_name='Password')),
                ('URL', models.CharField(blank=True, max_length=150, verbose_name='URL')),
                ('FechaExpiracion', models.DateTimeField(blank=True, verbose_name='Fecha Expiración')),
                ('Nota', models.TextField(null=True, verbose_name='Nota')),
                ('Fecha', models.DateTimeField(blank=True, verbose_name='Fecha modificación')),
                ('idUsuario', models.CharField(blank=True, max_length=50, verbose_name='ID User')),
                ('Cloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud')),
                ('Folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.folder', verbose_name='Folder')),
            ],
        ),
        migrations.CreateModel(
            name='esx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvCenter', models.CharField(blank=True, max_length=150, verbose_name='vCenter')),
                ('ESX', models.CharField(blank=True, max_length=150, verbose_name='ESX')),
                ('Vendor', models.CharField(blank=True, max_length=150, verbose_name='Vendor')),
                ('Host', models.CharField(blank=True, max_length=150, verbose_name='Host')),
                ('idCloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoUser', models.CharField(max_length=100)),
                ('Perfil', models.CharField(max_length=100)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='idVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.vendor', verbose_name='Vendor'),
        ),
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActividad', models.CharField(blank=True, max_length=150, verbose_name='Actividad')),
                ('FechaInicio', models.DateTimeField(blank=True, verbose_name='Fecha Inicio')),
                ('FechaFin', models.CharField(blank=True, max_length=150, verbose_name='Fecha Fin')),
                ('HorasInvertidas', models.CharField(blank=True, max_length=50, verbose_name='Horas invertidas')),
                ('MinutosInvertidos', models.CharField(blank=True, max_length=50, verbose_name='Minutos invertidos')),
                ('IM', models.CharField(blank=True, max_length=150, verbose_name='IM')),
                ('RFC', models.CharField(blank=True, max_length=150, verbose_name='RFC')),
                ('SR', models.CharField(blank=True, max_length=150, verbose_name='SR')),
                ('Usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('Evento', models.CharField(blank=True, max_length=150, verbose_name='Evento')),
                ('Descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Status', models.CharField(blank=True, max_length=150, verbose_name='Status')),
                ('Avance', models.CharField(blank=True, max_length=150, verbose_name='Avance')),
                ('Solicitante', models.CharField(blank=True, max_length=100, verbose_name='Solicitante')),
                ('NombreTurnos', models.CharField(blank=True, max_length=100, verbose_name='NombreTurnos')),
                ('HO', models.CharField(blank=True, max_length=100, verbose_name='Home Office')),
                ('Tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo mejora')),
                ('Actividades', models.CharField(blank=True, max_length=100, verbose_name='Actividades')),
                ('Ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.ambiente', verbose_name='Ambiente')),
            ],
        ),
    ]
