# Generated by Django 3.2 on 2023-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Perfil',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
