# Generated by Django 3.2 on 2022-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='SR',
            field=models.CharField(blank=True, max_length=150, verbose_name='Service Request'),
        ),
    ]
