# Generated by Django 4.0.2 on 2022-02-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='CambioHW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.cambiohw', verbose_name='Cambio Hardware'),
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='Fecha',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='SR',
            field=models.CharField(blank=True, max_length=150, verbose_name='Service Request'),
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Descripción'),
        ),
    ]
