# Generated by Django 3.2 on 2023-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0002_auto_20230330_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefallas',
            name='EstatusSR',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='FechaCierre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fecha Cierre'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='FechaHoraSolicitud',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fecha Solicitud'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='FechaPrimerContacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fecha Primer Contacto'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='Resolucion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='Severidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Severidad'),
        ),
    ]
