# Generated by Django 3.2 on 2023-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0002_customuser_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='FechaInicio',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Inicio'),
        ),
    ]
