# Generated by Django 4.0.2 on 2022-02-14 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0002_alter_reportefallas_cambiohw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='Fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
