# Generated by Django 3.2 on 2022-06-08 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0002_alter_reportefallas_sr'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActividad', models.CharField(blank=True, max_length=150, verbose_name='Actividad')),
                ('FechaInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicio')),
                ('FechaFin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Fin')),
                ('HorasInvertidas', models.CharField(blank=True, max_length=50, verbose_name='Horas invertidas')),
            ],
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='RMA',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
