# Generated by Django 4.0.2 on 2022-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0003_alter_reportefallas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='Fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='Motivo',
            field=models.TextField(null=True),
        ),
    ]
