# Generated by Django 3.2 on 2022-06-08 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0003_auto_20220608_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='FechaFin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='FechaInicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Inicio'),
        ),
    ]
