# Generated by Django 3.2 on 2023-05-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0003_auto_20230420_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreIngeniero', models.CharField(blank=True, max_length=150, verbose_name='Ing. Asignado')),
                ('Proyecto', models.CharField(blank=True, max_length=150, verbose_name='Proyecto')),
                ('Avance', models.CharField(blank=True, max_length=150, verbose_name='Avance')),
                ('Status', models.CharField(blank=True, max_length=150, verbose_name='Status')),
                ('FechaAsignacion', models.DateTimeField(blank=True, verbose_name='Fecha asignación')),
                ('FechaFinal', models.DateTimeField(blank=True, verbose_name='Fecha final')),
            ],
        ),
    ]
