# Generated by Django 3.2 on 2023-06-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0004_ingactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cloud', models.CharField(blank=True, max_length=150, verbose_name='Cloud')),
                ('Titulo', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('Usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('Password', models.CharField(blank=True, max_length=150, verbose_name='Password')),
                ('URL', models.CharField(blank=True, max_length=150, verbose_name='URL')),
                ('FechaExpiracion', models.DateTimeField(blank=True, verbose_name='Fecha Expiración')),
                ('Nota', models.CharField(blank=True, max_length=150, verbose_name='Nota')),
            ],
        ),
        migrations.AddField(
            model_name='ingactividad',
            name='LiderTecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lider Técnico'),
        ),
        migrations.AlterField(
            model_name='ingactividad',
            name='NombreIngeniero',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ing. Asignado'),
        ),
    ]
