# Generated by Django 3.2 on 2022-06-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0004_auto_20220608_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='IM',
            field=models.CharField(blank=True, max_length=150, verbose_name='IM'),
        ),
    ]
