# Generated by Django 4.0.2 on 2022-02-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0004_alter_reportefallas_fecha_alter_reportefallas_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('Falla', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='CambioHW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.cambiohw', verbose_name='Cambio de hardware'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='TipoFalla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.tipofalla', verbose_name='Tipo de falla'),
        ),
    ]
