# Generated by Django 3.2 on 2022-06-21 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0005_actividades_im'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='Evento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='actividades',
            name='Usuario',
            field=models.CharField(blank=True, max_length=150, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
