# Generated by Django 3.2 on 2023-07-13 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0005_auto_20230614_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingactividad',
            name='LiderTecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ing. Asignado'),
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='FechaFix',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
