# Generated by Django 4.0.2 on 2022-02-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0005_tipofalla_alter_reportefallas_cambiohw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='Motivo',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportefallas',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Motivo'),
        ),
    ]
