# Generated by Django 4.0.2 on 2022-02-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0006_alter_reportefallas_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
