# Generated by Django 3.2 on 2023-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0006_auto_20230713_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepass',
            name='Cloud',
            field=models.CharField(blank=True, max_length=15, verbose_name='Cloud'),
        ),
        migrations.AlterField(
            model_name='keepass',
            name='Nota',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Nota'),
        ),
    ]
