# Generated by Django 3.2 on 2022-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0007_auto_20220622_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='Ambiente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='Avance',
            field=models.CharField(blank=True, max_length=150, verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='RFC',
            field=models.CharField(blank=True, max_length=150, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='SR',
            field=models.CharField(blank=True, max_length=150, verbose_name='SR'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='Status',
            field=models.CharField(blank=True, max_length=150, verbose_name='Status'),
        ),
    ]
