# Generated by Django 3.2 on 2023-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0007_auto_20230717_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepass',
            name='Folder',
            field=models.CharField(blank=True, max_length=15, verbose_name='Folder'),
        ),
    ]
