# Generated by Django 4.0.2 on 2022-02-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0007_alter_reportefallas_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['NombreAmbiente']},
        ),
        migrations.AlterModelOptions(
            name='cambiohw',
            options={'ordering': ['idHW']},
        ),
        migrations.AlterModelOptions(
            name='tipofalla',
            options={'ordering': ['Falla']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['NombreVendor']},
        ),
    ]
