# Generated by Django 3.2 on 2023-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0008_keepass_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepass',
            name='Folder',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folder'),
        ),
    ]
