# Generated by Django 4.0.2 on 2022-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0008_alter_ambiente_options_alter_cambiohw_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefallas',
            name='Fecha',
            field=models.CharField(max_length=50),
        ),
    ]
