# Generated by Django 3.2 on 2023-07-27 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0009_alter_keepass_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepass',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha modificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keepass',
            name='idUsuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario'),
        ),
    ]
