# Generated by Django 3.2 on 2022-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0009_actividades_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='NombreTurnos',
            field=models.CharField(blank=True, max_length=100, verbose_name='NombreTurnos'),
        ),
    ]
