# Generated by Django 4.0.2 on 2022-02-17 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0009_alter_reportefallas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportefallas',
            name='Motivo',
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idComponente', models.AutoField(primary_key=True, serialize=False)),
                ('Componente', models.CharField(max_length=100)),
                ('idVendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.vendor', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['Componente'],
            },
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='Componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.componente', verbose_name='Componente'),
        ),
    ]
