# Generated by Django 3.2 on 2022-02-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0010_remove_reportefallas_motivo_componente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cierreFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComentarioCierre', models.TextField(null=True, verbose_name='Comentario')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('idFAlla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.reportefallas', verbose_name='id_Falla')),
            ],
        ),
    ]
