# Generated by Django 3.2 on 2023-08-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0010_auto_20230727_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepass',
            name='idUsuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID User'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder', models.CharField(blank=True, max_length=200, verbose_name='Folder')),
                ('idCloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.keepass', verbose_name='Cloud')),
            ],
        ),
    ]
