# Generated by Django 3.2 on 2022-08-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0010_actividades_nombreturnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='FechaFin',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fecha Fin'),
        ),
    ]
