# Generated by Django 3.2 on 2022-09-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0011_alter_actividades_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='Ambiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.ambiente', verbose_name='Ambiente'),
        ),
    ]
