# Generated by Django 3.2 on 2023-08-01 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0011_auto_20230801_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('idCloud', models.AutoField(primary_key=True, serialize=False)),
                ('Cloud', models.CharField(blank=True, max_length=200, verbose_name='Cloud')),
            ],
        ),
        migrations.AlterField(
            model_name='keepass',
            name='Folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.folder', verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='idCloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud'),
        ),
        migrations.AlterField(
            model_name='keepass',
            name='Cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportinfra.cloud', verbose_name='Cloud'),
        ),
    ]
