# Generated by Django 3.2 on 2022-02-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0011_cierrefalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrefalla',
            name='idFAlla',
        ),
    ]
