# Generated by Django 3.2 on 2022-03-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0012_remove_cierrefalla_idfalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportefallas',
            name='TipoFalla',
        ),
        migrations.AddField(
            model_name='reportefallas',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.tipofalla', verbose_name='Categoria'),
        ),
    ]
