# Generated by Django 3.2 on 2023-08-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0012_auto_20230801_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepass',
            name='Nota',
            field=models.TextField(null=True, verbose_name='Nota'),
        ),
    ]
