# Generated by Django 3.2 on 2022-09-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportinfra', '0012_alter_actividades_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Usuario',
            field=models.CharField(blank=True, max_length=150, verbose_name='Usuario'),
        ),
    ]
