# Generated by Django 3.2 on 2022-03-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0013_auto_20220228_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoFalla',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['Categoria']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Falla',
            new_name='Categoria',
        ),
    ]
