# Generated by Django 3.2 on 2022-03-01 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0014_auto_20220228_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reportInfra.categoria', verbose_name='Vendor'),
        ),
    ]
