# Generated by Django 3.2 on 2022-03-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0015_vendor_idcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrefalla',
            name='idFAlla',
            field=models.TextField(null=True, verbose_name='Comentario'),
        ),
    ]
