# Generated by Django 3.2 on 2022-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportInfra', '0017_rename_idfalla_cierrefalla_idfalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefallas',
            name='RMA',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cierrefalla',
            name='idFalla',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='Service Request'),
            preserve_default=False,
        ),
    ]
